# see .env for image version env variables
# see repo/settings/environments for image version env variables for github actions
services:
  db:
    # https://github.com/docker-library/mysql/issues/275#issuecomment-636831964
    image: mysql:${MYSQL_VER}
    command: '--default-authentication-plugin=mysql_native_password'
    # command: '--default-authentication-plugin=mysql_native_password --log_error_verbosity=3' # mysql
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    #   - MYSQL_DATABASE=users
    #   - MYSQL_USER=users
    #   - MYSQL_PASSWORD_FILE=/run/secrets/users-password

  web:
    image: louking/tm-csv-connector-web:${APP_VER}
    build: 
      context: web
      args:
        - NGINX_VER=${NGINX_VER}
        - PHPMYADMIN_VER=${PHPMYADMIN_VER}
    restart: always
    networks:
      - frontend-network
    ports:
      - ${TM_CSV_CONNECTOR_PORT}:80
    # uncomment to debug
    # command: [nginx-debug, '-g', 'daemon off;']

  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VER}-fpm
    restart: always
    depends_on:
      - db
    networks:
      - backend-network
      - frontend-network
    environment:
      - PMA_ABSOLUTE_URI=http://phpmyadmin/phpmyadmin

  app:
    image: louking/tm-csv-connector-app:${APP_VER}
    build: 
      context: app
      args:
        - PYTHON_VER=${PYTHON_VER}
    restart: always
    depends_on:
      - db
    secrets:
      - db-password
      - tm-csv-connector-password
    networks:
      - backend-network
      - frontend-network
    # https://stackoverflow.com/a/24326540/799921
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
      - ./config:/config:ro
      # OUTPUT_DIR needs to be set in .env, using forward slashes, similar to
      # OUTPUT_DIR="c:/Users/lking/Documents/Lou's Software/test/time-machine/tm-csv-connector/file-output"
      - type: bind
        source: ${OUTPUT_DIR}
        target: /output_dir
    environment:
      - FLASK_DEBUG=True
      - APP_DATABASE=tm-csv-connector
      - APP_USER=tm-csv-connector
      - APP_PASSWORD_FILE=/run/secrets/tm-csv-connector-password
      - APP_VER=${APP_VER}
      - TZ=${TZ}
    # access log is in web container
    # command: ["./dbupgrade_and_run.sh", "gunicorn", "--reload", "--bind", "0.0.0.0:5000", "--access-logfile", "-", "--log-file", "-", "app:app"]
    command: ["./dbupgrade_and_run.sh", "gunicorn", "--reload", "--bind", "0.0.0.0:5000", "--log-file", "-", "app:app"]

volumes:
  db-data:

secrets:
  db-password:
    file: config/db/root-password.txt
  tm-csv-connector-password:
    file: config/db/tm-csv-connector-password.txt

networks:
  backend-network:
  frontend-network:
