services:
  # this is used for for rsync file transfer of leaderboard html files, not part of tm-csv-connector core functionality
  app:
    environment:
      - TM_CSV_CONNECTOR_PORT=${TM_CSV_CONNECTOR_PORT}
      - SIMULATION_MODE=True
    secrets:
      - mail-password
      - security-password-salt
      - super-admin-user-password

secrets:
  db-password:
    file: config/db/root-password.txt
  mail-password:
    file: config/db/mail-password.txt
  security-password-salt:
    file: config/db/security-password-salt.txt
  super-admin-user-password:
    file: config/db/super-admin-user-password.txt
