version: "3.8"

services:
  web:
    build: 
      context: web
      args:
        - NGINX_VER=${NGINX_VER}
        - PHPMYADMIN_VER=${PHPMYADMIN_VER}

  app:
    build: 
      context: app
      args:
        - PYTHON_VER=${PYTHON_VER}
