"""add simulationrun.next_scannedbib_id, simulationevent.etype Text

Revision ID: 15ab20ba5d74
Revises: fcfb6e0abe9d
Create Date: 2025-06-11 15:51:52.095096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15ab20ba5d74'
down_revision = 'fcfb6e0abe9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulationevent', schema=None) as batch_op:
        batch_op.alter_column('etype',
               existing_type=mysql.ENUM('timemachine', 'scan'),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('simulationrun', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_scannedbib_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('simulationrun_ibfk_3', 'scannedbib', ['next_scannedbib_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulationrun', schema=None) as batch_op:
        batch_op.drop_constraint('simulationrun_ibfk_3', type_='foreignkey')
        batch_op.drop_column('next_scannedbib_id')

    with op.batch_alter_table('simulationevent', schema=None) as batch_op:
        batch_op.alter_column('etype',
               existing_type=sa.Text(),
               type_=mysql.ENUM('timemachine', 'scan'),
               existing_nullable=False)

    # ### end Alembic commands ###
