"""add chipread table

Revision ID: 20f2a0c1c611
Revises: df648cc4abc9
Create Date: 2024-06-11 17:40:07.126176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f2a0c1c611'
down_revision = 'df648cc4abc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chipread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.String(length=1), nullable=True),
    sa.Column('receiver_id', sa.String(length=1), nullable=True),
    sa.Column('tag_id', sa.String(length=12), nullable=True),
    sa.Column('contig_ctr', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('types', sa.Text(), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chipread', schema=None) as batch_op:
        batch_op.create_index('rdr_date_tag_idx', ['reader_id', 'date', 'tag_id'], unique=False)
        batch_op.create_index('rdr_date_tag_time_idx', ['reader_id', 'date', 'tag_id', 'time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chipread', schema=None) as batch_op:
        batch_op.drop_index('rdr_date_tag_time_idx')
        batch_op.drop_index('rdr_date_tag_idx')

    op.drop_table('chipread')
    # ### end Alembic commands ###
