"""add simulation.description

Revision ID: 38495405d38d
Revises: 9f901401c7aa
Create Date: 2025-08-16 06:44:34.743101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38495405d38d'
down_revision = '9f901401c7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
