"""race: start_time is now float for subsecond precision

Revision ID: 5d4994a4dd0b
Revises: b2d22253f3be
Create Date: 2023-12-23 19:56:44.226087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d4994a4dd0b'
down_revision = 'b2d22253f3be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=mysql.TIME(),
               type_=sa.Double(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.Double(),
               type_=mysql.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
