"""add resultssnapshot table

Revision ID: 88ecb06e844d
Revises: ae3fb8072af4
Create Date: 2026-06-12 07:28:26.536290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ecb06e844d'
down_revision = 'ae3fb8072af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultssnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('scannedbibs_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultssnapshot')
    # ### end Alembic commands ###
