"""add simulationresult.correct, rename simulationvector to simulationexpected

Revision ID: 8d7aa774f349
Revises: 38495405d38d
Create Date: 2025-08-20 11:24:17.217893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d7aa774f349'
down_revision = '38495405d38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulationexpected',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('bibno', sa.Text(), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('simulationvector')
    with op.batch_alter_table('simulationresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulationresult', schema=None) as batch_op:
        batch_op.drop_column('correct')

    op.create_table('simulationvector',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time', mysql.FLOAT(), nullable=True),
    sa.Column('bibno', mysql.TEXT(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulation.id'], name='simulationvector_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('simulationexpected')
    # ### end Alembic commands ###
