"""add bib to chipread table

Revision ID: 93055c49b4d4
Revises: 48a65429a4bd
Create Date: 2024-06-13 18:27:36.796137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93055c49b4d4'
down_revision = '48a65429a4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chipread', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bib', sa.Integer(), nullable=True))
        batch_op.create_index('rdr_date_bib_idx', ['reader_id', 'date', 'bib'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chipread', schema=None) as batch_op:
        batch_op.drop_index('rdr_date_bib_idx')
        batch_op.drop_column('bib')

    # ### end Alembic commands ###
