"""add simulationrun.start_time

Revision ID: 9f901401c7aa
Revises: 15ab20ba5d74
Create Date: 2025-07-29 07:26:46.119220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f901401c7aa'
down_revision = '15ab20ba5d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulationrun', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Double(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulationrun', schema=None) as batch_op:
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
