"""race: add debounce_scans

Revision ID: bc03f0a27070
Revises: 88ecb06e844d
Create Date: 2026-10-10 07:02:04.179442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc03f0a27070'
down_revision = '88ecb06e844d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debounce_scans', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_column('debounce_scans')

    # ### end Alembic commands ###
