"""add scannedbib table

Revision ID: c059e4296731
Revises: 5d4994a4dd0b
Create Date: 2024-02-13 21:22:15.943816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c059e4296731'
down_revision = '5d4994a4dd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scannedbib',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('bibno', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scannedbib_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('result_ibfk_2', 'scannedbib', ['scannedbib_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_constraint('result_ibfk_2', type_='foreignkey')
        batch_op.drop_column('scannedbib_id')

    op.drop_table('scannedbib')
    # ### end Alembic commands ###
