"""race table: add next_scannedbib

Revision ID: df648cc4abc9
Revises: 0338048cfcc1
Create Date: 2024-02-28 20:32:40.948094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df648cc4abc9'
down_revision = '0338048cfcc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_scannedbib_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('race_ibfk_1', 'scannedbib', ['next_scannedbib_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_constraint('race_ibfk_1', type_='foreignkey')
        batch_op.drop_column('next_scannedbib_id')

    # ### end Alembic commands ###
