"""add simulationexpected.epsilon

Revision ID: e3825d7768b6
Revises: 8d7aa774f349
Create Date: 2025-08-22 11:03:31.973777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3825d7768b6'
down_revision = '8d7aa774f349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulationexpected', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epsilon', sa.Float(), nullable=True))

    # ### end Alembic commands ###

    # all existing expected results should have epsilon of 0
    from sqlalchemy.sql import table, column
    expected = table('simulationexpected',
                   column('epsilon', sa.Float())
                   )
    op.execute(
        expected.update()
        .values({'epsilon': op.inline_literal(0)})
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulationexpected', schema=None) as batch_op:
        batch_op.drop_column('epsilon')

    # ### end Alembic commands ###
