"""chipreader table; chipread.source

Revision ID: ed0b2cf33082
Revises: 93055c49b4d4
Create Date: 2024-07-12 11:44:05.444990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0b2cf33082'
down_revision = '93055c49b4d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chipreader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('reader_id', sa.String(length=1), nullable=True),
    sa.Column('ipaddr', sa.Text(), nullable=True),
    sa.Column('fport', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chipread', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.Text(), nullable=True))

    # ### end Alembic commands ###

    # default chipread.source = 'file'
    from sqlalchemy.sql import table, column
    chipread = table('chipread',
                        column('source', sa.Text())
                     )
    op.execute(
        chipread.update().\
            values({'source': op.inline_literal('file')})
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chipread', schema=None) as batch_op:
        batch_op.drop_column('source')

    op.drop_table('chipreader')
    # ### end Alembic commands ###
