"""chipread and chipbib tables: add race_id

Revision ID: f2fecc209205
Revises: a269f3c37c6e
Create Date: 2025-03-21 13:56:40.092719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2fecc209205'
down_revision = 'a269f3c37c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chipbib', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_id', sa.Integer(), nullable=True))
        batch_op.drop_index('tag_idx')
        batch_op.create_index('race_tag_idx', ['race_id', 'tag_id'], unique=False)
        batch_op.create_foreign_key('chipbib_ibfk_1', 'race', ['race_id'], ['id'])

    with op.batch_alter_table('chipread', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('chipread_ibfk_1', 'race', ['race_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chipread', schema=None) as batch_op:
        batch_op.drop_constraint('chipread_ibfk_1', type_='foreignkey')
        batch_op.drop_column('race_id')

    with op.batch_alter_table('chipbib', schema=None) as batch_op:
        batch_op.drop_constraint('chipbib_ibfk_1', type_='foreignkey')
        batch_op.drop_index('race_tag_idx')
        batch_op.create_index('tag_idx', ['tag_id'], unique=False)
        batch_op.drop_column('race_id')

    # ### end Alembic commands ###
